import drill from "@/assets/p-drill.jpg";
import generator from "@/assets/p-generator.jpg";
import jackhammer from "@/assets/p-jackhammer.jpg";
import grinder from "@/assets/p-grinder.jpg";
import welder from "@/assets/p-welder.jpg";
import mixer from "@/assets/p-mixer.jpg";
import ladder from "@/assets/p-ladder.jpg";
import washer from "@/assets/p-washer.jpg";
import safety from "@/assets/p-safety.jpg";
import chainsaw from "@/assets/p-chainsaw.jpg";
import compressor from "@/assets/p-compressor.jpg";
import saw from "@/assets/p-saw.jpg";
import rotary from "@/assets/p-rotary.jpg";
import scaffold from "@/assets/p-scaffold.jpg";

const toolImages = import.meta.glob("/src/assets/tools/*.jpg", {
  eager: true,
  import: "default",
}) as Record<string, string>;

export type Product = {
  id: string;
  slug: string;
  name: string;
  brand: string;
  category: string;
  image: string;
  images: string[];
  rentalPerDay: number;
  salePrice: number;
  deposit: number;
  rating: number;
  reviews: number;
  stock: number;
  badge?: "trending" | "deal" | "new" | "popular";
  specs: Record<string, string>;
  description: string;
};

export const CATEGORIES = [
  { slug: "power-tools", name: "Power Tools", icon: "Drill" },
  { slug: "generators", name: "Generators", icon: "Zap" },
  { slug: "ladders", name: "Ladders & Scaffold", icon: "Ladder" },
  { slug: "welding", name: "Welding", icon: "Flame" },
  { slug: "concrete", name: "Concrete", icon: "Cog" },
  { slug: "cleaning", name: "Cleaning & Drying", icon: "Droplets" },
  { slug: "demolition", name: "Demolition", icon: "Hammer" },
  { slug: "safety", name: "Safety Gear", icon: "HardHat" },
  { slug: "air-tools", name: "Air Tools", icon: "Wind" },
] as const;

export const BRANDS = [
  "Bosch",
  "DeWalt",
  "Makita",
  "Hilti",
  "Honda",
  "Kärcher",
  "Lincoln",
  "Stihl",
  "Metabo",
];

type Seed = Omit<Product, "images"> & { images?: string[] };

const RAW: Seed[] = [
  // POWER TOOLS (12)
  {
    id: "1",
    slug: "cordless-hammer-drill-18v",
    name: "Cordless Hammer Drill 18V",
    brand: "DeWalt",
    category: "power-tools",
    image: drill,
    rentalPerDay: 349,
    salePrice: 12499,
    deposit: 2000,
    rating: 4.8,
    reviews: 284,
    stock: 12,
    badge: "trending",
    specs: {
      Power: "18V Li-ion",
      "Motor Capacity": "820W",
      Weight: "1.9 kg",
      Chuck: "13 mm",
      Warranty: "1 year",
    },
    description:
      "Professional-grade brushless hammer drill with 3-mode operation for concrete, wood and metal.",
  },
  {
    id: "2",
    slug: "angle-grinder-125mm",
    name: "Angle Grinder 125 mm",
    brand: "Bosch",
    category: "power-tools",
    image: grinder,
    rentalPerDay: 199,
    salePrice: 5499,
    deposit: 1000,
    rating: 4.6,
    reviews: 512,
    stock: 24,
    specs: {
      Power: "1100W",
      "Disc Size": "125 mm",
      "No-load Speed": "11000 rpm",
      Weight: "2.1 kg",
    },
    description:
      "Compact, high-torque grinder for cutting, grinding and polishing metal and stone.",
  },
  {
    id: "3",
    slug: "circular-saw-185mm",
    name: "Circular Saw 185 mm",
    brand: "Makita",
    category: "power-tools",
    image: saw,
    rentalPerDay: 299,
    salePrice: 8999,
    deposit: 1500,
    rating: 4.7,
    reviews: 198,
    stock: 15,
    badge: "popular",
    specs: { Power: "1400W", "Blade Size": "185 mm", "Cut Depth": "66 mm", Weight: "3.4 kg" },
    description: "Precision circular saw for straight-line cuts in timber, ply and softboard.",
  },
  {
    id: "4",
    slug: "rotary-hammer-sds-plus",
    name: "Rotary Hammer SDS-Plus",
    brand: "Hilti",
    category: "power-tools",
    image: rotary,
    rentalPerDay: 449,
    salePrice: 18999,
    deposit: 3000,
    rating: 4.9,
    reviews: 142,
    stock: 8,
    badge: "new",
    specs: { Power: "900W", "Impact Energy": "3.5 J", Chuck: "SDS-plus", Weight: "3.9 kg" },
    description:
      "Heavy-duty rotary hammer with active vibration reduction for anchor and through-hole drilling.",
  },
  {
    id: "5",
    slug: "cordless-impact-driver-18v",
    name: "Cordless Impact Driver 18V",
    brand: "Makita",
    category: "power-tools",
    image: drill,
    rentalPerDay: 279,
    salePrice: 9499,
    deposit: 1500,
    rating: 4.7,
    reviews: 321,
    stock: 20,
    specs: { Power: "18V", Torque: "180 Nm", "No-load Speed": "3600 rpm", Weight: "1.5 kg" },
    description: "Compact brushless impact driver ideal for framing, decking and fasteners.",
  },
  {
    id: "6",
    slug: "cut-off-saw-14inch",
    name: 'Cut-Off Saw 14"',
    brand: "Stihl",
    category: "power-tools",
    image: saw,
    rentalPerDay: 499,
    salePrice: 22000,
    deposit: 3500,
    rating: 4.6,
    reviews: 88,
    stock: 6,
    specs: { Power: "2200W", "Disc Size": "355 mm", "Cut Depth": "127 mm", Weight: "9.8 kg" },
    description: "High-speed abrasive cut-off saw for rebar, pipe and steel section.",
  },
  {
    id: "7",
    slug: "chainsaw-16inch-petrol",
    name: 'Petrol Chainsaw 16"',
    brand: "Stihl",
    category: "power-tools",
    image: chainsaw,
    rentalPerDay: 399,
    salePrice: 15999,
    deposit: 2500,
    rating: 4.8,
    reviews: 174,
    stock: 9,
    badge: "popular",
    specs: { Engine: "36cc", "Bar Length": "16 inch", Fuel: "Petrol 2-stroke", Weight: "4.3 kg" },
    description: "Reliable petrol chainsaw for site clearing, tree work and demolition.",
  },
  {
    id: "8",
    slug: "orbital-sander-125mm",
    name: "Random Orbital Sander",
    brand: "Bosch",
    category: "power-tools",
    image: grinder,
    rentalPerDay: 149,
    salePrice: 4499,
    deposit: 800,
    rating: 4.5,
    reviews: 203,
    stock: 22,
    specs: { Power: "300W", "Pad Size": "125 mm", Weight: "1.4 kg" },
    description: "Dust-extracted orbital sander for finishing timber, plaster and metal.",
  },
  {
    id: "9",
    slug: "reciprocating-saw",
    name: "Reciprocating Saw",
    brand: "DeWalt",
    category: "power-tools",
    image: saw,
    rentalPerDay: 249,
    salePrice: 7499,
    deposit: 1200,
    rating: 4.6,
    reviews: 156,
    stock: 14,
    specs: { Power: "1100W", Stroke: "28 mm", Speed: "2900 spm", Weight: "3.5 kg" },
    description: "Fast-cutting reciprocating saw for demolition, pipe and remodel work.",
  },
  {
    id: "10",
    slug: "heat-gun-2000w",
    name: "Heat Gun 2000W",
    brand: "Metabo",
    category: "power-tools",
    image: drill,
    rentalPerDay: 129,
    salePrice: 3499,
    deposit: 600,
    rating: 4.4,
    reviews: 98,
    stock: 18,
    specs: { Power: "2000W", "Temp Range": "50–600 °C", Weight: "0.8 kg" },
    description: "Dual-temp heat gun for shrink-wrapping, stripping paint and joining pipe.",
  },
  {
    id: "11",
    slug: "planer-82mm",
    name: "Electric Planer 82 mm",
    brand: "Bosch",
    category: "power-tools",
    image: grinder,
    rentalPerDay: 229,
    salePrice: 6499,
    deposit: 1000,
    rating: 4.5,
    reviews: 74,
    stock: 11,
    specs: { Power: "850W", "Cut Width": "82 mm", "Cut Depth": "3 mm", Weight: "2.9 kg" },
    description: "Portable planer for smoothing and sizing timber on site.",
  },
  {
    id: "12",
    slug: "jigsaw-variable-speed",
    name: "Jigsaw Variable Speed",
    brand: "Makita",
    category: "power-tools",
    image: saw,
    rentalPerDay: 179,
    salePrice: 5299,
    deposit: 900,
    rating: 4.6,
    reviews: 212,
    stock: 16,
    specs: { Power: "720W", Stroke: "26 mm", "Cut Depth (wood)": "135 mm", Weight: "2.4 kg" },
    description: "Precise variable-speed jigsaw for curved cuts in wood, metal and plastic.",
  },

  // GENERATORS (6)
  {
    id: "13",
    slug: "diesel-generator-5-kva",
    name: "Silent Diesel Generator 5 kVA",
    brand: "Honda",
    category: "generators",
    image: generator,
    rentalPerDay: 1499,
    salePrice: 89999,
    deposit: 10000,
    rating: 4.9,
    reviews: 132,
    stock: 4,
    badge: "popular",
    specs: {
      Power: "5 kVA",
      "Fuel Type": "Diesel",
      Voltage: "230V",
      "Run Time": "10 hrs @ 50%",
      Weight: "78 kg",
      Warranty: "2 years",
    },
    description: "Whisper-quiet inverter generator ideal for site power, events and backup.",
  },
  {
    id: "14",
    slug: "petrol-generator-2-kva",
    name: "Petrol Generator 2 kVA",
    brand: "Honda",
    category: "generators",
    image: generator,
    rentalPerDay: 699,
    salePrice: 38000,
    deposit: 5000,
    rating: 4.7,
    reviews: 210,
    stock: 8,
    specs: { Power: "2 kVA", "Fuel Type": "Petrol", Voltage: "230V", Weight: "29 kg" },
    description: "Portable inverter generator for tools, lighting and small appliances.",
  },
  {
    id: "15",
    slug: "diesel-generator-15-kva",
    name: "Diesel Generator 15 kVA",
    brand: "Honda",
    category: "generators",
    image: generator,
    rentalPerDay: 2999,
    salePrice: 189000,
    deposit: 20000,
    rating: 4.8,
    reviews: 76,
    stock: 3,
    badge: "deal",
    specs: {
      Power: "15 kVA",
      "Fuel Type": "Diesel",
      Voltage: "415V 3-phase",
      "Run Time": "12 hrs",
      Weight: "420 kg",
    },
    description: "Three-phase diesel gen-set for medium sites and construction offices.",
  },
  {
    id: "16",
    slug: "diesel-generator-30-kva",
    name: "Diesel Generator 30 kVA",
    brand: "Honda",
    category: "generators",
    image: generator,
    rentalPerDay: 4499,
    salePrice: 329000,
    deposit: 35000,
    rating: 4.9,
    reviews: 41,
    stock: 2,
    specs: { Power: "30 kVA", Voltage: "415V 3-phase", "Fuel Tank": "120 L", "Run Time": "14 hrs" },
    description: "Heavy-duty 3-phase generator for tower cranes and site distribution.",
  },
  {
    id: "17",
    slug: "inverter-generator-3kva",
    name: "Inverter Generator 3 kVA",
    brand: "Honda",
    category: "generators",
    image: generator,
    rentalPerDay: 999,
    salePrice: 59000,
    deposit: 7000,
    rating: 4.8,
    reviews: 118,
    stock: 6,
    badge: "new",
    specs: { Power: "3 kVA", "Fuel Type": "Petrol", Voltage: "230V", Noise: "58 dB" },
    description: "Ultra-quiet inverter generator with clean sine-wave output for electronics.",
  },
  {
    id: "18",
    slug: "portable-power-station-2kwh",
    name: "Portable Power Station 2 kWh",
    brand: "Honda",
    category: "generators",
    image: generator,
    rentalPerDay: 799,
    salePrice: 74000,
    deposit: 8000,
    rating: 4.6,
    reviews: 63,
    stock: 5,
    specs: { Capacity: "2000 Wh", Output: "2400W", Ports: "AC · USB-C · DC", Weight: "22 kg" },
    description: "Solar-ready battery power station for indoor and low-noise operation.",
  },

  // LADDERS & SCAFFOLD (6)
  {
    id: "19",
    slug: "aluminum-extension-ladder-20ft",
    name: "Aluminum Extension Ladder 20 ft",
    brand: "Bosch",
    category: "ladders",
    image: ladder,
    rentalPerDay: 249,
    salePrice: 8999,
    deposit: 1500,
    rating: 4.4,
    reviews: 210,
    stock: 18,
    specs: { Height: "6.1 m", Material: "Aluminum", "Load Capacity": "150 kg", Weight: "12 kg" },
    description: "Lightweight, corrosion-resistant extension ladder with anti-slip feet.",
  },
  {
    id: "20",
    slug: "a-frame-ladder-8ft",
    name: "A-Frame Step Ladder 8 ft",
    brand: "Bosch",
    category: "ladders",
    image: ladder,
    rentalPerDay: 149,
    salePrice: 4999,
    deposit: 800,
    rating: 4.5,
    reviews: 301,
    stock: 26,
    specs: { Height: "2.4 m", "Load Capacity": "120 kg", Material: "Aluminum", Weight: "7 kg" },
    description: "Stable A-frame ladder for indoor electrical, painting and light work.",
  },
  {
    id: "21",
    slug: "scaffold-tower-4m",
    name: "Mobile Scaffold Tower 4 m",
    brand: "Bosch",
    category: "ladders",
    image: scaffold,
    rentalPerDay: 899,
    salePrice: 52000,
    deposit: 6000,
    rating: 4.7,
    reviews: 88,
    stock: 5,
    badge: "popular",
    specs: {
      "Working Height": "4 m",
      Platform: "1.8 × 0.7 m",
      "Load Capacity": "200 kg",
      Material: "Aluminum",
    },
    description: "Modular mobile tower with lockable castors for façade and interior work.",
  },
  {
    id: "22",
    slug: "scaffold-tower-6m",
    name: "Mobile Scaffold Tower 6 m",
    brand: "Bosch",
    category: "ladders",
    image: scaffold,
    rentalPerDay: 1299,
    salePrice: 78000,
    deposit: 9000,
    rating: 4.7,
    reviews: 52,
    stock: 3,
    specs: { "Working Height": "6 m", Platform: "2.0 × 0.7 m", "Load Capacity": "200 kg" },
    description: "Two-lift scaffold tower for medium-height façade and painting work.",
  },
  {
    id: "23",
    slug: "telescopic-ladder-4-4m",
    name: "Telescopic Ladder 4.4 m",
    brand: "Bosch",
    category: "ladders",
    image: ladder,
    rentalPerDay: 199,
    salePrice: 6799,
    deposit: 1000,
    rating: 4.5,
    reviews: 127,
    stock: 14,
    badge: "trending",
    specs: { "Extended Height": "4.4 m", Closed: "0.9 m", "Load Capacity": "150 kg" },
    description: "Compact telescopic ladder that folds down to fit a car boot.",
  },
  {
    id: "24",
    slug: "platform-trestle-2m",
    name: "Platform Trestle 2 m",
    brand: "Bosch",
    category: "ladders",
    image: scaffold,
    rentalPerDay: 249,
    salePrice: 9500,
    deposit: 1500,
    rating: 4.4,
    reviews: 44,
    stock: 10,
    specs: { "Platform Height": "2 m", "Load Capacity": "180 kg", Material: "Aluminum" },
    description: "Portable trestle platform for finishing, tiling and ceiling work.",
  },

  // WELDING (5)
  {
    id: "25",
    slug: "mig-welder-250a",
    name: "MIG Welder 250A Inverter",
    brand: "Lincoln",
    category: "welding",
    image: welder,
    rentalPerDay: 999,
    salePrice: 62000,
    deposit: 8000,
    rating: 4.8,
    reviews: 74,
    stock: 6,
    badge: "new",
    specs: {
      Output: "250A",
      Voltage: "230V",
      "Duty Cycle": "60%",
      Weight: "24 kg",
      Warranty: "2 years",
    },
    description: "Industrial MIG/MAG welder for fabrication and structural steel work.",
  },
  {
    id: "26",
    slug: "arc-welder-200a",
    name: "ARC Welder 200A",
    brand: "Lincoln",
    category: "welding",
    image: welder,
    rentalPerDay: 449,
    salePrice: 18500,
    deposit: 3000,
    rating: 4.6,
    reviews: 189,
    stock: 12,
    specs: { Output: "200A", Voltage: "230V", "Duty Cycle": "35%", Weight: "6 kg" },
    description: "Compact inverter stick welder for site repair and rebar work.",
  },
  {
    id: "27",
    slug: "tig-welder-200a",
    name: "TIG Welder 200A AC/DC",
    brand: "Lincoln",
    category: "welding",
    image: welder,
    rentalPerDay: 899,
    salePrice: 54000,
    deposit: 7000,
    rating: 4.8,
    reviews: 52,
    stock: 5,
    badge: "popular",
    specs: { Output: "200A", Type: "AC/DC", "Duty Cycle": "40%", Weight: "18 kg" },
    description: "Precision TIG welder for stainless steel, aluminum and thin sheet work.",
  },
  {
    id: "28",
    slug: "plasma-cutter-40a",
    name: "Plasma Cutter 40A",
    brand: "Lincoln",
    category: "welding",
    image: welder,
    rentalPerDay: 799,
    salePrice: 44000,
    deposit: 6000,
    rating: 4.7,
    reviews: 64,
    stock: 4,
    specs: { Output: "40A", "Cut Thickness": "12 mm", Voltage: "230V", Weight: "12 kg" },
    description: "Compressed-air plasma cutter for fast, clean cuts in mild steel and SS.",
  },
  {
    id: "29",
    slug: "welding-helmet-auto",
    name: "Auto-Darkening Welding Helmet",
    brand: "Lincoln",
    category: "welding",
    image: safety,
    rentalPerDay: 99,
    salePrice: 3999,
    deposit: 500,
    rating: 4.5,
    reviews: 288,
    stock: 30,
    specs: { Shade: "9–13 auto", Sensors: "4", Reaction: "1/25000 s" },
    description: "Solar-assisted auto-darkening helmet with adjustable shade.",
  },

  // CONCRETE (5)
  {
    id: "30",
    slug: "concrete-mixer-1-bag",
    name: "Concrete Mixer 1 Bag",
    brand: "Makita",
    category: "concrete",
    image: mixer,
    rentalPerDay: 799,
    salePrice: 45000,
    deposit: 5000,
    rating: 4.5,
    reviews: 88,
    stock: 5,
    badge: "popular",
    specs: {
      Capacity: "1 bag (50 kg)",
      "Drum Volume": "180 L",
      Power: "1 HP motor",
      Weight: "165 kg",
    },
    description: "Portable site mixer with reinforced steel drum and heavy-duty gearbox.",
  },
  {
    id: "31",
    slug: "concrete-mixer-2-bag",
    name: "Concrete Mixer 2 Bag",
    brand: "Makita",
    category: "concrete",
    image: mixer,
    rentalPerDay: 1199,
    salePrice: 68000,
    deposit: 7000,
    rating: 4.6,
    reviews: 52,
    stock: 4,
    specs: {
      Capacity: "2 bag (100 kg)",
      "Drum Volume": "350 L",
      Power: "2 HP motor",
      Weight: "260 kg",
    },
    description: "Higher-throughput mixer for slab pours and multi-storey work.",
  },
  {
    id: "32",
    slug: "needle-vibrator-38mm",
    name: "Concrete Needle Vibrator 38 mm",
    brand: "Makita",
    category: "concrete",
    image: mixer,
    rentalPerDay: 299,
    salePrice: 11500,
    deposit: 1500,
    rating: 4.5,
    reviews: 71,
    stock: 9,
    specs: { Motor: "1500W", Needle: "38 mm × 5 m", Frequency: "12000 vpm" },
    description: "Immersion vibrator for de-airing freshly poured concrete.",
  },
  {
    id: "33",
    slug: "power-trowel-36inch",
    name: 'Walk-Behind Power Trowel 36"',
    brand: "Honda",
    category: "concrete",
    image: mixer,
    rentalPerDay: 1499,
    salePrice: 98000,
    deposit: 10000,
    rating: 4.7,
    reviews: 38,
    stock: 3,
    badge: "new",
    specs: { Rotor: "36 inch", Engine: "5.5 HP petrol", Weight: "78 kg" },
    description: "Petrol-powered trowel for smooth, hard-troweled floor finishes.",
  },
  {
    id: "34",
    slug: "plate-compactor-90kg",
    name: "Plate Compactor 90 kg",
    brand: "Honda",
    category: "concrete",
    image: mixer,
    rentalPerDay: 1099,
    salePrice: 65000,
    deposit: 8000,
    rating: 4.6,
    reviews: 67,
    stock: 5,
    specs: { Weight: "90 kg", "Plate Size": "500 × 400 mm", "Centrifugal Force": "15 kN" },
    description: "Petrol vibrating plate for compacting sub-base, sand and paving.",
  },

  // CLEANING (5)
  {
    id: "35",
    slug: "pressure-washer-2000psi",
    name: "Pressure Washer 2000 PSI",
    brand: "Kärcher",
    category: "cleaning",
    image: washer,
    rentalPerDay: 599,
    salePrice: 24999,
    deposit: 3000,
    rating: 4.7,
    reviews: 341,
    stock: 9,
    badge: "trending",
    specs: {
      Pressure: "2000 PSI",
      "Flow Rate": "7.5 L/min",
      Power: "2100W",
      Weight: "16 kg",
      Warranty: "1 year",
    },
    description: "Professional cold-water pressure washer for vehicles, facades and site cleanup.",
  },
  {
    id: "36",
    slug: "pressure-washer-3000psi",
    name: "Pressure Washer 3000 PSI",
    brand: "Kärcher",
    category: "cleaning",
    image: washer,
    rentalPerDay: 899,
    salePrice: 39900,
    deposit: 5000,
    rating: 4.8,
    reviews: 156,
    stock: 6,
    badge: "popular",
    specs: { Pressure: "3000 PSI", "Flow Rate": "9.5 L/min", Power: "2800W", Weight: "22 kg" },
    description: "High-pressure washer for tough industrial cleaning and paint prep.",
  },
  {
    id: "37",
    slug: "wet-dry-vacuum-30L",
    name: "Wet & Dry Vacuum 30 L",
    brand: "Kärcher",
    category: "cleaning",
    image: washer,
    rentalPerDay: 299,
    salePrice: 11500,
    deposit: 1500,
    rating: 4.6,
    reviews: 224,
    stock: 14,
    specs: { Capacity: "30 L", Power: "1400W", Suction: "22 kPa", Weight: "9 kg" },
    description: "Site vacuum for construction debris, water spills and dust extraction.",
  },
  {
    id: "38",
    slug: "floor-scrubber-walk",
    name: "Walk-Behind Floor Scrubber",
    brand: "Kärcher",
    category: "cleaning",
    image: washer,
    rentalPerDay: 1099,
    salePrice: 82000,
    deposit: 9000,
    rating: 4.7,
    reviews: 44,
    stock: 3,
    specs: { "Working Width": "430 mm", Tank: "25 L", Power: "Battery" },
    description: "Battery scrubber-drier for warehouse and commercial floor cleaning.",
  },
  {
    id: "39",
    slug: "hot-water-pressure-washer",
    name: "Hot Water Pressure Washer",
    brand: "Kärcher",
    category: "cleaning",
    image: washer,
    rentalPerDay: 1499,
    salePrice: 118000,
    deposit: 12000,
    rating: 4.8,
    reviews: 36,
    stock: 2,
    badge: "new",
    specs: { Pressure: "2500 PSI", "Max Temp": "80 °C", "Flow Rate": "9 L/min" },
    description: "Hot-water pressure washer for degreasing, workshop and food-service.",
  },

  // DEMOLITION (5)
  {
    id: "40",
    slug: "demolition-jack-hammer",
    name: "Demolition Jack Hammer 30 kg",
    brand: "Hilti",
    category: "demolition",
    image: jackhammer,
    rentalPerDay: 1899,
    salePrice: 154000,
    deposit: 15000,
    rating: 4.7,
    reviews: 96,
    stock: 3,
    badge: "deal",
    specs: {
      Power: "1600W",
      "Impact Energy": "60 J",
      Weight: "30 kg",
      "Blow Rate": "1050 bpm",
      Warranty: "1 year",
    },
    description: "Heavy-duty breaker for concrete demolition, road-cutting and foundation work.",
  },
  {
    id: "41",
    slug: "breaker-hammer-11kg",
    name: "Breaker Hammer 11 kg",
    brand: "Hilti",
    category: "demolition",
    image: jackhammer,
    rentalPerDay: 899,
    salePrice: 78000,
    deposit: 8000,
    rating: 4.7,
    reviews: 112,
    stock: 5,
    specs: { Power: "1500W", "Impact Energy": "25 J", Weight: "11 kg", Chuck: "SDS-max" },
    description: "Mid-weight demolition hammer for wall breaking and chiselling.",
  },
  {
    id: "42",
    slug: "core-drill-152mm",
    name: "Diamond Core Drill 152 mm",
    brand: "Hilti",
    category: "demolition",
    image: rotary,
    rentalPerDay: 1299,
    salePrice: 98000,
    deposit: 10000,
    rating: 4.8,
    reviews: 58,
    stock: 4,
    badge: "popular",
    specs: { Power: "2200W", "Max Diameter": "152 mm", Speed: "850 rpm" },
    description: "Wet diamond core drill for through-holes in concrete and masonry.",
  },
  {
    id: "43",
    slug: "floor-saw-350mm",
    name: "Petrol Floor Saw 350 mm",
    brand: "Stihl",
    category: "demolition",
    image: saw,
    rentalPerDay: 1499,
    salePrice: 118000,
    deposit: 12000,
    rating: 4.6,
    reviews: 31,
    stock: 2,
    specs: { Blade: "350 mm", "Cut Depth": "125 mm", Engine: "9 HP petrol" },
    description: "Walk-behind floor saw for cutting expansion joints and slab openings.",
  },
  {
    id: "44",
    slug: "wall-chaser-150mm",
    name: "Wall Chaser 150 mm",
    brand: "Hilti",
    category: "demolition",
    image: grinder,
    rentalPerDay: 599,
    salePrice: 32000,
    deposit: 4000,
    rating: 4.6,
    reviews: 47,
    stock: 6,
    specs: { Power: "1900W", "Cut Width": "8–43 mm", "Cut Depth": "45 mm" },
    description: "Dust-extracted wall chaser for electrical and plumbing channels.",
  },

  // SAFETY (4)
  {
    id: "45",
    slug: "safety-kit-standard",
    name: "Standard Safety Kit",
    brand: "Bosch",
    category: "safety",
    image: safety,
    rentalPerDay: 79,
    salePrice: 1499,
    deposit: 200,
    rating: 4.6,
    reviews: 412,
    stock: 60,
    badge: "popular",
    specs: {
      Includes: "Helmet · Vest · Gloves · Goggles",
      Standard: "IS 2925",
      Sizes: "M / L / XL",
    },
    description: "Compliance-ready safety kit for site visitors and short-term crew.",
  },
  {
    id: "46",
    slug: "fall-arrest-harness",
    name: "Full-Body Fall-Arrest Harness",
    brand: "Bosch",
    category: "safety",
    image: safety,
    rentalPerDay: 149,
    salePrice: 4500,
    deposit: 800,
    rating: 4.7,
    reviews: 184,
    stock: 22,
    specs: {
      Standard: "EN 361",
      "Load Capacity": "140 kg",
      Attachments: "Dorsal · Sternal · Side",
    },
    description: "5-point full-body harness for working at heights, IS/EN certified.",
  },
  {
    id: "47",
    slug: "safety-boots-steel-toe",
    name: "Steel-Toe Safety Boots",
    brand: "Bosch",
    category: "safety",
    image: safety,
    rentalPerDay: 59,
    salePrice: 2299,
    deposit: 300,
    rating: 4.5,
    reviews: 301,
    stock: 40,
    specs: { Standard: "IS 15298", Toe: "200 J steel", Sole: "PU anti-slip", Sizes: "6–11" },
    description: "Site-ready safety boots with slip-resistant sole and oil-resistant upper.",
  },
  {
    id: "48",
    slug: "traffic-safety-cone-set",
    name: "Traffic Safety Cone Set (10)",
    brand: "Bosch",
    category: "safety",
    image: safety,
    rentalPerDay: 129,
    salePrice: 3200,
    deposit: 400,
    rating: 4.4,
    reviews: 76,
    stock: 30,
    specs: { Quantity: "10 cones", Height: "750 mm", Material: "PVC reflective" },
    description: "High-visibility PVC cones for lane closures and site perimeter.",
  },

  // AIR TOOLS (3)
  {
    id: "49",
    slug: "air-compressor-50L",
    name: "Air Compressor 50 L",
    brand: "Metabo",
    category: "air-tools",
    image: compressor,
    rentalPerDay: 499,
    salePrice: 22500,
    deposit: 3000,
    rating: 4.6,
    reviews: 143,
    stock: 7,
    badge: "trending",
    specs: { Tank: "50 L", Power: "2 HP", Pressure: "10 bar", Flow: "250 L/min" },
    description: "Direct-drive air compressor for pneumatic tools, blowers and inflation.",
  },
  {
    id: "50",
    slug: "air-compressor-100L",
    name: "Air Compressor 100 L",
    brand: "Metabo",
    category: "air-tools",
    image: compressor,
    rentalPerDay: 799,
    salePrice: 38000,
    deposit: 5000,
    rating: 4.7,
    reviews: 82,
    stock: 5,
    specs: { Tank: "100 L", Power: "3 HP", Pressure: "12 bar", Flow: "420 L/min" },
    description: "Twin-cylinder air compressor for workshop and continuous-duty use.",
  },
  {
    id: "51",
    slug: "pneumatic-nailer-framing",
    name: "Pneumatic Framing Nailer",
    brand: "Metabo",
    category: "air-tools",
    image: compressor,
    rentalPerDay: 299,
    salePrice: 9800,
    deposit: 1500,
    rating: 4.6,
    reviews: 98,
    stock: 12,
    badge: "new",
    specs: { "Nail Length": "50–90 mm", Pressure: "5–8 bar", Magazine: "60 nails" },
    description: "Air-powered framing nailer for formwork, decking and pallet assembly.",
  },
  {
    id: "52",
    slug: "paint-mixer-1200w",
    name: "Paint Mixer 1200W",
    brand: "Bosch",
    category: "power-tools",
    image: drill,
    rentalPerDay: 50,
    salePrice: 5499,
    deposit: 800,
    rating: 4.6,
    reviews: 44,
    stock: 10,
    badge: "new",
    specs: { Power: "1200W", "Mixing Paddle": "140 mm", Speed: "0–700 rpm" },
    description: "Variable-speed paint and mortar mixer for coatings, putty and adhesives.",
  },
  {
    id: "53",
    slug: "floor-dryer-3-speed",
    name: "Industrial Floor Dryer 3-Speed",
    brand: "Kärcher",
    category: "cleaning",
    image: washer,
    rentalPerDay: 250,
    salePrice: 12999,
    deposit: 1500,
    rating: 4.5,
    reviews: 39,
    stock: 6,
    specs: { Airflow: "3-speed", Power: "900W", Coverage: "Large rooms" },
    description: "High-velocity floor dryer for post-cleaning, painting and water-damage jobs.",
  },
  {
    id: "54",
    slug: "tile-cutter-24-inch",
    name: "Manual Tile Cutter 24 inch",
    brand: "Bosch",
    category: "power-tools",
    image: saw,
    rentalPerDay: 50,
    salePrice: 3999,
    deposit: 500,
    rating: 4.5,
    reviews: 71,
    stock: 12,
    specs: { CuttingLength: "24 inch", Material: "Ceramic and vitrified tile", Weight: "8 kg" },
    description: "Smooth-score tile cutter for clean, repeatable site cuts.",
  },
  {
    id: "55",
    slug: "marble-cutter-4-inch",
    name: "Marble Cutter 4 inch",
    brand: "Makita",
    category: "power-tools",
    image: grinder,
    rentalPerDay: 50,
    salePrice: 4499,
    deposit: 700,
    rating: 4.6,
    reviews: 63,
    stock: 14,
    specs: { Power: "1200W", Blade: "4 inch", CutDepth: "34 mm" },
    description: "Compact wet/dry cutter for marble, tile and masonry.",
  },
  {
    id: "56",
    slug: "bench-drill-13mm",
    name: "Bench Drill 13 mm",
    brand: "Bosch",
    category: "power-tools",
    image: drill,
    rentalPerDay: 50,
    salePrice: 13999,
    deposit: 1800,
    rating: 4.6,
    reviews: 35,
    stock: 4,
    specs: { Chuck: "13 mm", Power: "500W", Speed: "5 settings" },
    description: "Stable bench-mounted drill for accurate workshop drilling.",
  },
  {
    id: "57",
    slug: "aluminium-ladder-40-inch",
    name: "Aluminium Step Ladder 40 inch",
    brand: "Bosch",
    category: "ladders",
    image: ladder,
    rentalPerDay: 50,
    salePrice: 2499,
    deposit: 500,
    rating: 4.5,
    reviews: 91,
    stock: 16,
    specs: { Height: "40 inch", Material: "Aluminium", Load: "120 kg" },
    description: "Compact anti-slip aluminium ladder for indoor maintenance and painting.",
  },
  {
    id: "58",
    slug: "aluminium-ladder-60-inch",
    name: "Aluminium Step Ladder 60 inch",
    brand: "Bosch",
    category: "ladders",
    image: ladder,
    rentalPerDay: 70,
    salePrice: 3499,
    deposit: 600,
    rating: 4.5,
    reviews: 74,
    stock: 12,
    specs: { Height: "60 inch", Material: "Aluminium", Load: "120 kg" },
    description: "Medium-height aluminium ladder for electrical and decorating work.",
  },
  {
    id: "59",
    slug: "aluminium-ladder-100-inch",
    name: "Aluminium Extension Ladder 100 inch",
    brand: "Bosch",
    category: "ladders",
    image: ladder,
    rentalPerDay: 110,
    salePrice: 5999,
    deposit: 1000,
    rating: 4.6,
    reviews: 58,
    stock: 8,
    specs: { Height: "100 inch", Material: "Aluminium", Load: "150 kg" },
    description: "Long-reach extension ladder with non-slip feet and secure locks.",
  },

  // POWER TOOLS — EXTRA (6)
  {
    id: "60",
    slug: "auto-feed-screw-gun-18v",
    name: "Auto-Feed Screw Gun 18V",
    brand: "Makita",
    category: "power-tools",
    image: drill,
    rentalPerDay: 249,
    salePrice: 8999,
    deposit: 1200,
    rating: 4.6,
    reviews: 143,
    stock: 14,
    specs: {
      Power: "18V Li-ion",
      "Screw Length": "25–55 mm",
      "Magazine Capacity": "50 screws",
      Weight: "1.8 kg",
    },
    description: "Auto-feed collated screw gun for rapid drywall and decking installation.",
  },
  {
    id: "61",
    slug: "magnetic-core-drill-press",
    name: "Magnetic Core Drill Press",
    brand: "Hilti",
    category: "power-tools",
    image: rotary,
    rentalPerDay: 599,
    salePrice: 32000,
    deposit: 4000,
    rating: 4.7,
    reviews: 58,
    stock: 6,
    badge: "new",
    specs: {
      Power: "1200W",
      "Magnet Force": "1500 kgf",
      "Drill Diameter": "12–50 mm",
      Weight: "13.5 kg",
    },
    description: "Magnetic-base core drill for precision holes in structural steel beams.",
  },
  {
    id: "62",
    slug: "folding-sawhorse-pair-steel",
    name: "Folding Sawhorse Pair (Steel)",
    brand: "Metabo",
    category: "power-tools",
    image: saw,
    rentalPerDay: 99,
    salePrice: 3499,
    deposit: 400,
    rating: 4.4,
    reviews: 76,
    stock: 22,
    specs: {
      Material: "Powder-coated steel",
      "Load Capacity": "500 kg per pair",
      Height: "79 cm",
      Foldable: "Yes",
    },
    description: "Heavy-duty folding sawhorse pair for cutting, sawing and workbench setups.",
  },
  {
    id: "63",
    slug: "cordless-hammer-drill-20v-brushless",
    name: "Cordless Hammer Drill 20V Brushless",
    brand: "DeWalt",
    category: "power-tools",
    image: drill,
    rentalPerDay: 399,
    salePrice: 15999,
    deposit: 2200,
    rating: 4.8,
    reviews: 97,
    stock: 10,
    badge: "trending",
    specs: {
      Power: "20V Li-ion Brushless",
      "Motor Capacity": "950W",
      Chuck: "13 mm",
      Weight: "2.1 kg",
    },
    description: "Brushless upgrade of our standard hammer drill with 30% longer runtime.",
  },
  {
    id: "64",
    slug: "angle-grinder-230mm-heavy-duty",
    name: "Angle Grinder 230 mm Heavy Duty",
    brand: "Bosch",
    category: "power-tools",
    image: grinder,
    rentalPerDay: 299,
    salePrice: 8499,
    deposit: 1500,
    rating: 4.5,
    reviews: 132,
    stock: 16,
    specs: {
      Power: "2200W",
      "Disc Size": "230 mm",
      "No-load Speed": "6600 rpm",
      Weight: "5.1 kg",
    },
    description: "Large-disc grinder for heavy cutting and surface grinding on steel and stone.",
  },
  {
    id: "65",
    slug: "cordless-circular-saw-165mm",
    name: "Cordless Circular Saw 165 mm",
    brand: "Makita",
    category: "power-tools",
    image: saw,
    rentalPerDay: 249,
    salePrice: 7499,
    deposit: 1200,
    rating: 4.6,
    reviews: 88,
    stock: 12,
    specs: { Power: "18V Li-ion", "Blade Size": "165 mm", "Cut Depth": "57 mm", Weight: "2.8 kg" },
    description: "Cordless site saw for quick, cable-free rip cuts in timber and plywood.",
  },

  // GENERATORS — EXTRA (6)
  {
    id: "66",
    slug: "diesel-generator-7-5-kva",
    name: "Diesel Generator 7.5 kVA",
    brand: "Honda",
    category: "generators",
    image: generator,
    rentalPerDay: 1899,
    salePrice: 109000,
    deposit: 12000,
    rating: 4.8,
    reviews: 64,
    stock: 4,
    specs: {
      Power: "7.5 kVA",
      "Fuel Type": "Diesel",
      Voltage: "230V",
      "Run Time": "11 hrs @ 50%",
      Weight: "110 kg",
    },
    description: "Mid-size diesel gen-set bridging site power gaps between 5 and 15 kVA.",
  },
  {
    id: "67",
    slug: "diesel-generator-20-kva",
    name: "Diesel Generator 20 kVA",
    brand: "Honda",
    category: "generators",
    image: generator,
    rentalPerDay: 3699,
    salePrice: 249000,
    deposit: 25000,
    rating: 4.8,
    reviews: 37,
    stock: 3,
    specs: {
      Power: "20 kVA",
      Voltage: "415V 3-phase",
      "Fuel Tank": "90 L",
      "Run Time": "13 hrs",
    },
    description: "Three-phase gen-set for larger site offices and tower crane support.",
  },
  {
    id: "68",
    slug: "diesel-generator-40-kva",
    name: "Diesel Generator 40 kVA",
    brand: "Honda",
    category: "generators",
    image: generator,
    rentalPerDay: 5499,
    salePrice: 399000,
    deposit: 40000,
    rating: 4.9,
    reviews: 22,
    stock: 2,
    badge: "deal",
    specs: {
      Power: "40 kVA",
      Voltage: "415V 3-phase",
      "Fuel Tank": "150 L",
      "Run Time": "15 hrs",
    },
    description: "Our largest gen-set for full-site power on major builds and events.",
  },
  {
    id: "69",
    slug: "petrol-generator-3-5-kva",
    name: "Petrol Generator 3.5 kVA",
    brand: "Honda",
    category: "generators",
    image: generator,
    rentalPerDay: 849,
    salePrice: 46000,
    deposit: 6000,
    rating: 4.7,
    reviews: 94,
    stock: 7,
    specs: { Power: "3.5 kVA", "Fuel Type": "Petrol", Voltage: "230V", Weight: "38 kg" },
    description: "Step-up petrol generator for larger tool loads and short power cuts.",
  },
  {
    id: "70",
    slug: "inverter-generator-2kva-silent",
    name: "Inverter Generator 2 kVA Silent",
    brand: "Honda",
    category: "generators",
    image: generator,
    rentalPerDay: 749,
    salePrice: 42000,
    deposit: 5000,
    rating: 4.7,
    reviews: 71,
    stock: 8,
    specs: { Power: "2 kVA", "Fuel Type": "Petrol", Voltage: "230V", Noise: "52 dB" },
    description: "Compact silent inverter unit for indoor finishing work and events.",
  },
  {
    id: "71",
    slug: "portable-power-station-1kwh",
    name: "Portable Power Station 1 kWh",
    brand: "Honda",
    category: "generators",
    image: generator,
    rentalPerDay: 499,
    salePrice: 42000,
    deposit: 4000,
    rating: 4.5,
    reviews: 39,
    stock: 6,
    specs: { Capacity: "1000 Wh", Output: "1200W", Ports: "AC · USB-C · DC", Weight: "12 kg" },
    description: "Lightweight battery station for lighting, laptops and site cameras.",
  },

  // LADDERS & SCAFFOLD — EXTRA (4)
  {
    id: "72",
    slug: "aluminum-extension-ladder-28ft",
    name: "Aluminum Extension Ladder 28 ft",
    brand: "Bosch",
    category: "ladders",
    image: ladder,
    rentalPerDay: 349,
    salePrice: 12999,
    deposit: 2000,
    rating: 4.5,
    reviews: 96,
    stock: 9,
    specs: { Height: "8.5 m", Material: "Aluminum", "Load Capacity": "150 kg", Weight: "18 kg" },
    description: "Long-reach extension ladder for roofline and multi-storey access.",
  },
  {
    id: "73",
    slug: "a-frame-ladder-5ft",
    name: "A-Frame Step Ladder 5 ft",
    brand: "Bosch",
    category: "ladders",
    image: ladder,
    rentalPerDay: 99,
    salePrice: 3299,
    deposit: 500,
    rating: 4.4,
    reviews: 118,
    stock: 30,
    specs: { Height: "1.5 m", "Load Capacity": "120 kg", Material: "Aluminum", Weight: "4.5 kg" },
    description: "Compact step ladder for household jobs and low-reach maintenance.",
  },
  {
    id: "74",
    slug: "mobile-scaffold-tower-3m",
    name: "Mobile Scaffold Tower 3 m",
    brand: "Bosch",
    category: "ladders",
    image: scaffold,
    rentalPerDay: 699,
    salePrice: 42000,
    deposit: 5000,
    rating: 4.6,
    reviews: 61,
    stock: 6,
    specs: {
      "Working Height": "3 m",
      Platform: "1.4 × 0.7 m",
      "Load Capacity": "200 kg",
      Material: "Aluminum",
    },
    description: "Single-lift scaffold tower for compact interior and corridor work.",
  },
  {
    id: "75",
    slug: "platform-trestle-3m",
    name: "Platform Trestle 3 m",
    brand: "Bosch",
    category: "ladders",
    image: scaffold,
    rentalPerDay: 349,
    salePrice: 13500,
    deposit: 2000,
    rating: 4.4,
    reviews: 33,
    stock: 8,
    specs: { "Platform Height": "3 m", "Load Capacity": "180 kg", Material: "Aluminum" },
    description: "Taller trestle platform for ceiling and high-wall finishing work.",
  },

  // WELDING — EXTRA (5)
  {
    id: "76",
    slug: "mig-welder-160a-compact",
    name: "MIG Welder 160A Compact",
    brand: "Lincoln",
    category: "welding",
    image: welder,
    rentalPerDay: 599,
    salePrice: 38000,
    deposit: 5000,
    rating: 4.6,
    reviews: 68,
    stock: 8,
    specs: { Output: "160A", Voltage: "230V", "Duty Cycle": "40%", Weight: "14 kg" },
    description: "Lightweight single-phase MIG welder for home workshops and light fabrication.",
  },
  {
    id: "77",
    slug: "arc-welder-140a-portable",
    name: "ARC Welder 140A Portable",
    brand: "Lincoln",
    category: "welding",
    image: welder,
    rentalPerDay: 299,
    salePrice: 11500,
    deposit: 2000,
    rating: 4.5,
    reviews: 154,
    stock: 18,
    specs: { Output: "140A", Voltage: "230V", "Duty Cycle": "30%", Weight: "4.2 kg" },
    description: "Ultra-portable stick welder for quick site repairs and small jobs.",
  },
  {
    id: "78",
    slug: "tig-welder-250a-ac-dc-pro",
    name: "TIG Welder 250A AC/DC Pro",
    brand: "Lincoln",
    category: "welding",
    image: welder,
    rentalPerDay: 1199,
    salePrice: 72000,
    deposit: 9000,
    rating: 4.9,
    reviews: 29,
    stock: 3,
    badge: "new",
    specs: { Output: "250A", Type: "AC/DC", "Duty Cycle": "50%", Weight: "22 kg" },
    description: "Professional-grade TIG set for thicker aluminum and pressure-vessel work.",
  },
  {
    id: "79",
    slug: "plasma-cutter-60a-industrial",
    name: "Plasma Cutter 60A Industrial",
    brand: "Lincoln",
    category: "welding",
    image: welder,
    rentalPerDay: 1099,
    salePrice: 62000,
    deposit: 8000,
    rating: 4.8,
    reviews: 34,
    stock: 3,
    specs: { Output: "60A", "Cut Thickness": "20 mm", Voltage: "415V", Weight: "18 kg" },
    description: "Industrial plasma cutter for thicker plate and structural steel cutting.",
  },
  {
    id: "80",
    slug: "welding-face-shield-passive",
    name: "Welding Face Shield Passive",
    brand: "Lincoln",
    category: "welding",
    image: safety,
    rentalPerDay: 49,
    salePrice: 1499,
    deposit: 200,
    rating: 4.3,
    reviews: 91,
    stock: 26,
    specs: { Shade: "Fixed shade 10", Material: "Polycarbonate", Weight: "0.4 kg" },
    description: "Budget passive face shield for grinding and short-duration welding.",
  },

  // CONCRETE — EXTRA (5)
  {
    id: "81",
    slug: "mini-concrete-chop-saw-4inch",
    name: "Mini Concrete Chop Saw 4-inch",
    brand: "Makita",
    category: "concrete",
    image: saw,
    rentalPerDay: 149,
    salePrice: 4999,
    deposit: 800,
    rating: 4.4,
    reviews: 82,
    stock: 20,
    specs: {
      Power: "1050W",
      "Blade Size": "4 inch (100 mm)",
      "Cut Depth": "30 mm",
      Weight: "2.4 kg",
    },
    description: "Handheld mini cutter for tight-space concrete and masonry trimming.",
  },
  {
    id: "82",
    slug: "concrete-chop-saw-7inch",
    name: "Concrete Chop Saw 7-inch",
    brand: "Makita",
    category: "concrete",
    image: saw,
    rentalPerDay: 249,
    salePrice: 8999,
    deposit: 1200,
    rating: 4.5,
    reviews: 65,
    stock: 12,
    specs: {
      Power: "2000W",
      "Blade Size": "7 inch (180 mm)",
      "Cut Depth": "60 mm",
      Weight: "4.6 kg",
    },
    description: "Mid-size cutter for kerbstone, block and paving slab work.",
  },
  {
    id: "83",
    slug: "concrete-mixer-half-bag-mini",
    name: "Concrete Mixer 0.5 Bag Mini",
    brand: "Makita",
    category: "concrete",
    image: mixer,
    rentalPerDay: 499,
    salePrice: 28000,
    deposit: 3000,
    rating: 4.3,
    reviews: 54,
    stock: 8,
    specs: {
      Capacity: "0.5 bag (25 kg)",
      "Drum Volume": "90 L",
      Power: "0.5 HP motor",
      Weight: "85 kg",
    },
    description: "Compact mixer for small repairs, patchwork and garden slabs.",
  },
  {
    id: "84",
    slug: "concrete-needle-vibrator-50mm",
    name: "Concrete Needle Vibrator 50 mm",
    brand: "Makita",
    category: "concrete",
    image: mixer,
    rentalPerDay: 399,
    salePrice: 15500,
    deposit: 2000,
    rating: 4.6,
    reviews: 41,
    stock: 7,
    specs: { Motor: "2200W", Needle: "50 mm × 6 m", Frequency: "11000 vpm" },
    description: "Larger-diameter vibrator for de-airing mass concrete pours.",
  },
  {
    id: "85",
    slug: "power-trowel-46inch",
    name: 'Walk-Behind Power Trowel 46"',
    brand: "Honda",
    category: "concrete",
    image: mixer,
    rentalPerDay: 1899,
    salePrice: 125000,
    deposit: 13000,
    rating: 4.7,
    reviews: 19,
    stock: 2,
    specs: { Rotor: "46 inch", Engine: "8 HP petrol", Weight: "98 kg" },
    description: "Wider-blade trowel for large slab pours needing fewer passes.",
  },

  // CLEANING — EXTRA (4)
  {
    id: "86",
    slug: "pressure-washer-1500psi-compact",
    name: "Pressure Washer 1500 PSI Compact",
    brand: "Kärcher",
    category: "cleaning",
    image: washer,
    rentalPerDay: 399,
    salePrice: 16999,
    deposit: 2000,
    rating: 4.5,
    reviews: 176,
    stock: 15,
    specs: { Pressure: "1500 PSI", "Flow Rate": "6 L/min", Power: "1800W", Weight: "11 kg" },
    description: "Entry-level washer for vehicles, patios and small site cleanup.",
  },
  {
    id: "87",
    slug: "wet-dry-vacuum-50l-industrial",
    name: "Wet & Dry Vacuum 50 L Industrial",
    brand: "Kärcher",
    category: "cleaning",
    image: washer,
    rentalPerDay: 399,
    salePrice: 15999,
    deposit: 2000,
    rating: 4.6,
    reviews: 98,
    stock: 10,
    specs: { Capacity: "50 L", Power: "1800W", Suction: "25 kPa", Weight: "13 kg" },
    description: "Larger-tank vacuum for bigger debris and dust-extraction jobs.",
  },
  {
    id: "88",
    slug: "floor-scrubber-compact-380mm",
    name: "Walk-Behind Floor Scrubber Compact",
    brand: "Kärcher",
    category: "cleaning",
    image: washer,
    rentalPerDay: 899,
    salePrice: 68000,
    deposit: 7000,
    rating: 4.5,
    reviews: 27,
    stock: 4,
    specs: { "Working Width": "380 mm", Tank: "18 L", Power: "Battery" },
    description: "Narrower scrubber for corridors, retail floors and tight aisles.",
  },
  {
    id: "89",
    slug: "hot-water-pressure-washer-diesel",
    name: "Hot Water Pressure Washer Diesel-Fired",
    brand: "Kärcher",
    category: "cleaning",
    image: washer,
    rentalPerDay: 1699,
    salePrice: 132000,
    deposit: 14000,
    rating: 4.7,
    reviews: 18,
    stock: 2,
    badge: "new",
    specs: { Pressure: "2800 PSI", "Max Temp": "90 °C", "Flow Rate": "11 L/min" },
    description: "Standalone diesel-fired hot-water unit for sites without power hookup.",
  },

  // DEMOLITION — EXTRA (4)
  {
    id: "90",
    slug: "concrete-cut-off-saw-12inch",
    name: "Concrete Cut-Off Saw 12-inch",
    brand: "Stihl",
    category: "demolition",
    image: saw,
    rentalPerDay: 699,
    salePrice: 42000,
    deposit: 5000,
    rating: 4.6,
    reviews: 46,
    stock: 5,
    specs: {
      Power: "5 HP petrol",
      "Blade Size": "12 inch (300 mm)",
      "Cut Depth": "110 mm",
      Weight: "10 kg",
    },
    description: "Handheld petrol cut-off saw for kerbs, pipes and reinforced masonry.",
  },
  {
    id: "91",
    slug: "demolition-jack-hammer-45kg",
    name: "Demolition Jack Hammer 45 kg Heavy",
    brand: "Hilti",
    category: "demolition",
    image: jackhammer,
    rentalPerDay: 2499,
    salePrice: 198000,
    deposit: 20000,
    rating: 4.8,
    reviews: 41,
    stock: 2,
    specs: { Power: "2000W", "Impact Energy": "80 J", Weight: "45 kg", "Blow Rate": "980 bpm" },
    description: "Our heaviest breaker for foundation removal and thick slab demolition.",
  },
  {
    id: "92",
    slug: "core-drill-202mm-large-bore",
    name: "Core Drill 202 mm Large Bore",
    brand: "Hilti",
    category: "demolition",
    image: rotary,
    rentalPerDay: 1699,
    salePrice: 128000,
    deposit: 13000,
    rating: 4.7,
    reviews: 26,
    stock: 3,
    specs: { Power: "2600W", "Max Diameter": "202 mm", Speed: "650 rpm" },
    description: "Large-bore wet core drill for duct, pipe and services penetrations.",
  },
  {
    id: "93",
    slug: "wall-chaser-230mm-twin-blade",
    name: "Wall Chaser 230 mm Twin Blade",
    brand: "Hilti",
    category: "demolition",
    image: grinder,
    rentalPerDay: 799,
    salePrice: 44000,
    deposit: 5000,
    rating: 4.6,
    reviews: 33,
    stock: 4,
    specs: { Power: "2400W", "Cut Width": "8–43 mm", "Cut Depth": "65 mm" },
    description: "Larger twin-blade chaser for deeper conduit and pipe channels.",
  },

  // SAFETY — EXTRA (4)
  {
    id: "94",
    slug: "complete-ppe-kit-premium",
    name: "Complete PPE Kit Premium",
    brand: "Bosch",
    category: "safety",
    image: safety,
    rentalPerDay: 129,
    salePrice: 2499,
    deposit: 300,
    rating: 4.7,
    reviews: 156,
    stock: 35,
    badge: "popular",
    specs: {
      Includes: "Helmet · Vest · Gloves · Goggles · Ear Protection",
      Standard: "IS 2925 / EN 397",
      Sizes: "M / L / XL",
    },
    description: "Upgraded kit adding ear protection and cut-resistant gloves for longer jobs.",
  },
  {
    id: "95",
    slug: "fall-arrest-harness-double-hook",
    name: "Fall Arrest Harness Double Hook",
    brand: "Bosch",
    category: "safety",
    image: safety,
    rentalPerDay: 179,
    salePrice: 5200,
    deposit: 900,
    rating: 4.7,
    reviews: 88,
    stock: 16,
    specs: {
      Standard: "EN 361",
      "Load Capacity": "140 kg",
      Attachments: "Dorsal · Sternal · Twin Side Hooks",
    },
    description: "Twin-lanyard harness for continuous tie-off while moving along scaffolding.",
  },
  {
    id: "96",
    slug: "safety-boots-steel-toe-size-set",
    name: "Safety Boots Steel Toe (Size Set)",
    brand: "Bosch",
    category: "safety",
    image: safety,
    rentalPerDay: 59,
    salePrice: 2299,
    deposit: 300,
    rating: 4.4,
    reviews: 142,
    stock: 50,
    specs: { Standard: "IS 15298", Toe: "200 J steel", Sole: "PU anti-slip", Sizes: "Set of 6–11" },
    description: "Bulk size-run of steel-toe boots for outfitting a full site crew.",
  },
  {
    id: "97",
    slug: "barricade-tape-cone-combo",
    name: "Barricade Tape & Cone Combo Set",
    brand: "Bosch",
    category: "safety",
    image: safety,
    rentalPerDay: 99,
    salePrice: 2400,
    deposit: 300,
    rating: 4.3,
    reviews: 52,
    stock: 24,
    specs: { Quantity: "10 cones + 100 m tape", Height: "750 mm", Material: "PVC reflective" },
    description: "Cones bundled with reflective barricade tape for full perimeter setup.",
  },

  // AIR TOOLS — EXTRA (3)
  {
    id: "98",
    slug: "air-compressor-25l-compact",
    name: "Air Compressor 25 L Compact",
    brand: "Metabo",
    category: "air-tools",
    image: compressor,
    rentalPerDay: 349,
    salePrice: 14500,
    deposit: 2000,
    rating: 4.4,
    reviews: 61,
    stock: 10,
    specs: { Tank: "25 L", Power: "1.5 HP", Pressure: "8 bar", Flow: "180 L/min" },
    description: "Lightweight compressor for nailers, blowers and small inflation jobs.",
  },
  {
    id: "99",
    slug: "air-compressor-200l-industrial",
    name: "Air Compressor 200 L Industrial",
    brand: "Metabo",
    category: "air-tools",
    image: compressor,
    rentalPerDay: 1199,
    salePrice: 58000,
    deposit: 7000,
    rating: 4.8,
    reviews: 24,
    stock: 2,
    badge: "new",
    specs: { Tank: "200 L", Power: "5 HP", Pressure: "14 bar", Flow: "650 L/min" },
    description: "Large twin-tank compressor for continuous multi-tool workshop use.",
  },
  {
    id: "100",
    slug: "pneumatic-finish-nailer",
    name: "Pneumatic Finish Nailer",
    brand: "Metabo",
    category: "air-tools",
    image: compressor,
    rentalPerDay: 249,
    salePrice: 7800,
    deposit: 1200,
    rating: 4.5,
    reviews: 47,
    stock: 14,
    specs: { "Nail Gauge": "16 ga", "Nail Length": "25–63 mm", Magazine: "100 nails" },
    description: "Angled finish nailer for trim, mouldings and cabinetry fixing.",
  },
];

const productImageFiles: Record<string, string> = {
  "cordless-hammer-drill-18v": "hammer-drill.jpg",
  "angle-grinder-125mm": "angle-grinder.jpg",
  "circular-saw-185mm": "circular-saw.jpg",
  "rotary-hammer-sds-plus": "rotary-hammer.jpg",
  "cordless-impact-driver-18v": "impact-driver.jpg",
  "cut-off-saw-14inch": "cutoff-saw.jpg",
  "chainsaw-16inch-petrol": "chainsaw.jpg",
  "orbital-sander-125mm": "orbital-sander.jpg",
  "reciprocating-saw": "reciprocating-saw.jpg",
  "heat-gun-2000w": "heat-gun.jpg",
  "planer-82mm": "planer.jpg",
  "jigsaw-variable-speed": "jigsaw.jpg",
  "diesel-generator-5-kva": "gen-diesel-5kva.jpg",
  "petrol-generator-2-kva": "gen-petrol-2kva.jpg",
  "diesel-generator-15-kva": "gen-diesel-15kva.jpg",
  "diesel-generator-30-kva": "gen-diesel-30kva.jpg",
  "inverter-generator-3kva": "gen-inverter-3kva.jpg",
  "portable-power-station-2kwh": "power-station.jpg",
  "aluminum-extension-ladder-20ft": "ladder-ext-20.jpg",
  "a-frame-ladder-8ft": "ladder-aframe-8.jpg",
  "scaffold-tower-4m": "scaffold-4m.jpg",
  "scaffold-tower-6m": "scaffold-6m.jpg",
  "telescopic-ladder-4-4m": "ladder-telescopic.jpg",
  "platform-trestle-2m": "platform-trestle.jpg",
  "mig-welder-250a": "mig-welder.jpg",
  "arc-welder-200a": "arc-welder.jpg",
  "tig-welder-200a": "tig-welder.jpg",
  "plasma-cutter-40a": "plasma-cutter.jpg",
  "welding-helmet-auto": "welding-helmet.jpg",
  "concrete-mixer-1-bag": "concrete-mixer-1bag.jpg",
  "concrete-mixer-2-bag": "concrete-mixer-2bag.jpg",
  "needle-vibrator-38mm": "needle-vibrator.jpg",
  "power-trowel-36inch": "power-trowel.jpg",
  "plate-compactor-90kg": "plate-compactor.jpg",
  "pressure-washer-2000psi": "pressure-2000.jpg",
  "pressure-washer-3000psi": "pressure-3000.jpg",
  "wet-dry-vacuum-30L": "wet-dry-vac.jpg",
  "floor-scrubber-walk": "floor-scrubber.jpg",
  "hot-water-pressure-washer": "hot-water-pw.jpg",
  "demolition-jack-hammer": "big-breaker.jpg",
  "breaker-hammer-11kg": "small-breaker.jpg",
  "core-drill-152mm": "core-drill.jpg",
  "floor-saw-350mm": "floor-saw.jpg",
  "wall-chaser-150mm": "wall-chaser.jpg",
  "safety-kit-standard": "safety-kit.jpg",
  "fall-arrest-harness": "fall-harness.jpg",
  "safety-boots-steel-toe": "safety-boots.jpg",
  "traffic-safety-cone-set": "safety-cones.jpg",
  "air-compressor-50L": "air-comp-50L.jpg",
  "air-compressor-100L": "air-comp-100L.jpg",
  "pneumatic-nailer-framing": "nailer.jpg",
  "paint-mixer-1200w": "paint-mixer.jpg",
  "floor-dryer-3-speed": "floor-dryer.jpg",
  "tile-cutter-24-inch": "tile-cutter.jpg",
  "marble-cutter-4-inch": "marble-cutter.jpg",
  "bench-drill-13mm": "bench-drill.jpg",
  "aluminium-ladder-40-inch": "ladder-40in.jpg",
  "aluminium-ladder-60-inch": "ladder-60in.jpg",
  "aluminium-ladder-100-inch": "ladder-100in.jpg",
  "auto-feed-screw-gun-18v": "auto-drill.jpg",
  "magnetic-core-drill-press": "magnetic-drill.jpg",
  "folding-sawhorse-pair-steel": "sawhorse.jpg",
  "cordless-hammer-drill-20v-brushless": "hammer-drill.jpg",
  "angle-grinder-230mm-heavy-duty": "angle-grinder.jpg",
  "cordless-circular-saw-165mm": "circular-saw.jpg",
  "diesel-generator-7-5-kva": "gen-diesel-5kva.jpg",
  "diesel-generator-20-kva": "gen-diesel-15kva.jpg",
  "diesel-generator-40-kva": "gen-diesel-30kva.jpg",
  "petrol-generator-3-5-kva": "gen-petrol-2kva.jpg",
  "inverter-generator-2kva-silent": "gen-inverter-3kva.jpg",
  "portable-power-station-1kwh": "power-station.jpg",
  "aluminum-extension-ladder-28ft": "ladder-ext-20.jpg",
  "a-frame-ladder-5ft": "ladder-aframe-8.jpg",
  "mobile-scaffold-tower-3m": "scaffold-4m.jpg",
  "platform-trestle-3m": "platform-trestle.jpg",
  "mig-welder-160a-compact": "mig-welder.jpg",
  "arc-welder-140a-portable": "arc-welder.jpg",
  "tig-welder-250a-ac-dc-pro": "tig-welder.jpg",
  "plasma-cutter-60a-industrial": "plasma-cutter.jpg",
  "welding-face-shield-passive": "welding-helmet.jpg",
  "mini-concrete-chop-saw-4inch": "cutter-4in.jpg",
  "concrete-chop-saw-7inch": "cutter-7in.jpg",
  "concrete-mixer-half-bag-mini": "concrete-mixer-1bag.jpg",
  "concrete-needle-vibrator-50mm": "needle-vibrator.jpg",
  "power-trowel-46inch": "power-trowel.jpg",
  "pressure-washer-1500psi-compact": "pressure-2000.jpg",
  "wet-dry-vacuum-50l-industrial": "wet-dry-vac.jpg",
  "floor-scrubber-compact-380mm": "floor-scrubber.jpg",
  "hot-water-pressure-washer-diesel": "hot-water-pw.jpg",
  "concrete-cut-off-saw-12inch": "cutter-12in.jpg",
  "demolition-jack-hammer-45kg": "big-breaker.jpg",
  "core-drill-202mm-large-bore": "core-drill.jpg",
  "wall-chaser-230mm-twin-blade": "wall-chaser.jpg",
  "complete-ppe-kit-premium": "safety-kit.jpg",
  "fall-arrest-harness-double-hook": "fall-harness.jpg",
  "safety-boots-steel-toe-size-set": "safety-boots.jpg",
  "barricade-tape-cone-combo": "safety-cones.jpg",
  "air-compressor-25l-compact": "air-comp-50L.jpg",
  "air-compressor-200l-industrial": "air-comp-100L.jpg",
  "pneumatic-finish-nailer": "nailer.jpg",
};

export const PRODUCTS: Product[] = RAW.map((p) => {
  const filename = productImageFiles[p.slug];
  const image = filename ? toolImages[`/src/assets/tools/${filename}`] : p.image;
  return { ...p, image, images: [image] };
});

export const getProduct = (slug: string) => PRODUCTS.find((p) => p.slug === slug);
export const getProductById = (id: string) => PRODUCTS.find((p) => p.id === id);
export const byCategory = (cat: string) => PRODUCTS.filter((p) => p.category === cat);
